# Generated by Django 3.0.4 on 2020-03-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habittracker', '0003_auto_20200305_1848'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.UniqueConstraint(fields=('created_at', 'habit'), name='one_update_per_day'),
        ),
    ]
