# Generated by Django 3.0.4 on 2020-03-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habittracker', '0004_auto_20200305_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
