# Generated by Django 3.0.4 on 2020-03-06 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habittracker', '0006_remove_activity_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='result',
            new_name='result_nbr',
        ),
        migrations.RenameField(
            model_name='habit',
            old_name='goal_text',
            new_name='goal_description',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='category',
        ),
        migrations.AddField(
            model_name='habit',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habit',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
