# Generated by Django 3.0.4 on 2020-03-08 02:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habittracker', '0007_auto_20200306_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
