# Generated by Django 3.0.4 on 2020-03-08 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habittracker', '0009_habit_eval_method'),
        ('habittracker', '0008_auto_20200308_1037'),
    ]

    operations = [
    ]
