# Generated by Django 3.0.4 on 2020-03-08 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habittracker', '0011_auto_20200308_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='user',
        ),
    ]
